const $ = id => document.getElementById(id);
const SpeechRecognition = window.SpeechRecognition || window.webkitSpeechRecognition;
const STORAGE_KEY = 'hopi-kam-meetings-v2';
const DONE_KEY = 'hopi-kam-promises-done-v1';

const state = { recorder:null, stream:null, recognition:null, chunks:[], startedAt:0, timerId:null, recording:false, transcript:'', interim:'', analysis:null, currentId:null, markers:[], audioBlob:null };

function showView(id){document.querySelectorAll('.view').forEach(v=>v.classList.remove('active'));$(id)?.classList.add('active');document.querySelectorAll('.nav-btn').forEach(b=>b.classList.toggle('active',b.dataset.view===id));window.scrollTo({top:0,behavior:'smooth'});if(id==='tasksView')renderPromises();if(id==='customersView')renderCustomers()}
function toast(msg){const t=$('toast');if(!t)return;t.textContent=msg;t.classList.add('show');clearTimeout(t._x);t._x=setTimeout(()=>t.classList.remove('show'),3200)}
function esc(s=''){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#039;','"':'&quot;'}[c]))}
function wc(t){return (String(t||'').trim().match(/\S+/g)||[]).length}
function fmtTime(sec){sec=Math.max(0,Math.floor(sec||0));return `${String(Math.floor(sec/60)).padStart(2,'0')}:${String(sec%60).padStart(2,'0')}`}
function dateLabel(ts=Date.now()){return new Intl.DateTimeFormat('cs-CZ',{dateStyle:'medium',timeStyle:'short'}).format(new Date(ts))}
function elapsed(){return state.startedAt?(Date.now()-state.startedAt)/1000:0}

function resetMeeting(){try{state.recognition?.abort()}catch{};try{state.stream?.getTracks().forEach(t=>t.stop())}catch{};state.recorder=null;state.stream=null;state.recognition=null;state.chunks=[];state.startedAt=0;clearInterval(state.timerId);state.timerId=null;state.recording=false;state.transcript='';state.interim='';state.analysis=null;state.currentId=null;state.markers=[];state.audioBlob=null;if($('timer'))$('timer').textContent='00:00';if($('liveTranscript'))$('liveTranscript').textContent='Čekám na první slova…';if($('wordCount'))$('wordCount').textContent='0 slov';updateMarkerCount()}

async function startMeeting(){resetMeeting();const customer=$('customerName')?.value.trim()||'';$('recordTitle').textContent=customer||'Meeting';try{if(!navigator.mediaDevices?.getUserMedia)throw new Error('Mikrofon není dostupný.');state.stream=await navigator.mediaDevices.getUserMedia({audio:{echoCancellation:true,noiseSuppression:true,autoGainControl:true,channelCount:1}});if(!window.MediaRecorder)throw new Error('Nahrávání audia není podporované.');const types=['audio/mp4','audio/webm;codecs=opus','audio/webm'];const mime=types.find(t=>MediaRecorder.isTypeSupported?.(t));const opts={audioBitsPerSecond:64000};if(mime)opts.mimeType=mime;try{state.recorder=new MediaRecorder(state.stream,opts)}catch{state.recorder=mime?new MediaRecorder(state.stream,{mimeType:mime}):new MediaRecorder(state.stream)}state.recorder.ondataavailable=e=>{if(e.data?.size)state.chunks.push(e.data)};state.recorder.start(1000);state.recording=true;state.startedAt=Date.now();state.timerId=setInterval(()=>{$('timer').textContent=fmtTime(elapsed())},500);if(SpeechRecognition)startRecognition();else $('liveTranscript').textContent='Živý přepis není dostupný. Finální přepis vznikne po ukončení meetingu.';showView('recordView')}catch(e){try{state.stream?.getTracks().forEach(t=>t.stop())}catch{};toast(e.message||'Nepodařilo se spustit mikrofon.')}}
function startRecognition(){const r=new SpeechRecognition();r.lang='cs-CZ';r.continuous=true;r.interimResults=true;r.maxAlternatives=1;r.onresult=e=>{let interim='';for(let i=e.resultIndex;i<e.results.length;i++){const text=e.results[i][0].transcript.trim();if(e.results[i].isFinal&&text)state.transcript+=(state.transcript?' ':'')+text;else if(text)interim+=(interim?' ':'')+text}state.interim=interim;const all=[state.transcript,interim].filter(Boolean).join(' ');$('liveTranscript').textContent=all||'Čekám na první slova…';$('wordCount').textContent=`${wc(all)} slov`};r.onerror=e=>{if(!['no-speech','aborted'].includes(e.error))console.warn(e.error)};r.onend=()=>{if(state.recording){try{r.start()}catch{}}};try{r.start();state.recognition=r}catch{}}
async function finishRecording(){state.recording=false;clearInterval(state.timerId);try{state.recognition?.stop()}catch{};const mime=state.recorder?.mimeType||state.chunks?.[0]?.type||'audio/webm';if(state.recorder&&state.recorder.state!=='inactive')await new Promise(resolve=>{state.recorder.addEventListener('stop',resolve,{once:true});state.recorder.stop()});state.stream?.getTracks().forEach(t=>t.stop());state.audioBlob=new Blob(state.chunks,{type:mime});return state.audioBlob}
function addImportantMarker(){if(!state.recording)return;state.markers.push(Math.round(elapsed()));updateMarkerCount();toast(`Označeno ${fmtTime(state.markers[state.markers.length-1])}`)}
function updateMarkerCount(){if($('markerCount'))$('markerCount').textContent=`${state.markers.length} označených momentů`}

function history(){try{return JSON.parse(localStorage.getItem(STORAGE_KEY)||'[]')}catch{return[]}}
function saveHistory(items){localStorage.setItem(STORAGE_KEY,JSON.stringify(items.slice(0,100)))}
function latestForCustomer(customer){const key=String(customer||'').trim().toLocaleLowerCase('cs-CZ');if(!key)return null;return history().find(x=>String(x.customer||'').trim().toLocaleLowerCase('cs-CZ')===key)||null}
function previousContext(customer){const item=latestForCustomer(customer);if(!item)return null;const a=item.analysis||{};return {date:item.date,title:a.title||item.title,executive:a.executive,decisions:a.decisions,openPoints:a.openPoints,tasks:a.tasks,numbers:a.numbers,customerRequests:a.customerRequests,hopiPosition:a.hopiPosition,risks:a.risks,followUp:a.followUp}}
function saveCurrentMeeting(){if(!state.analysis)return;const h=history();const id=state.currentId||String(Date.now());state.currentId=id;const item={id,date:Date.now(),customer:$('customerName')?.value.trim()||'',email:$('emailTo')?.value.trim()||'',title:state.analysis.title||'Meeting',analysis:state.analysis,transcript:state.transcript};const idx=h.findIndex(x=>x.id===id);if(idx>=0)h[idx]=item;else h.unshift(item);saveHistory(h);renderPromises();renderCustomers()}

function fillList(id,items,empty='Bez zachycených bodů.'){const el=$(id);if(!el)return;el.innerHTML='';(items?.length?items:[empty]).forEach(x=>{const li=document.createElement('li');li.textContent=x;el.appendChild(li)})}
function renderBrief(){const a=state.analysis;if(!a)return;$('briefTitle').textContent=a.title||'Meeting Brief';$('executiveSummary').textContent=a.executive||'Bez hlavního závěru.';fillList('decisionsList',a.decisions);fillList('openPointsList',a.openPoints,'Žádné otevřené body.');fillList('promisesList',a.myPromises,'Žádný jednoznačný závazek HOPI.');fillList('changesList',a.changes,'Bez dostupného předchozího meetingu nebo bez změn.');fillList('numbersList',a.numbers,'Bez důležitých čísel.');fillList('requestsList',a.customerRequests);fillList('hopiList',a.hopiPosition);fillList('risksList',a.risks,'Bez zachyceného rizika.');fillList('followupList',a.followUp);$('recommendation').textContent=a.recommendation||'Bez interního doporučení.';const tt=$('tasksTable');tt.innerHTML='';if(!a.tasks?.length)tt.innerHTML='<div class="task-row"><div>Bez konkrétního úkolu</div><div class="task-owner">—</div><div class="task-deadline">—</div></div>';else a.tasks.forEach(t=>{const row=document.createElement('div');row.className='task-row';row.innerHTML=`<div>${esc(t.task)}<div class="task-side ${esc(t.side||'UNKNOWN')}">${t.side==='HOPI'?'HOPI':t.side==='CUSTOMER'?'Zákazník':'Neurčeno'}</div></div><div class="task-owner">${esc(t.owner||'doplnit')}</div><div class="task-deadline">${esc(t.deadline||'doplnit')}</div>`;tt.appendChild(row)});const src=$('sourceTranscript');src.innerHTML=`<div class="source-block"><p>${esc(state.transcript||'Přepis není dostupný.')}</p></div>`;saveCurrentMeeting();showView('briefView')}

function plainSummary(){const a=state.analysis||{};const out=[`${a.title||'Meeting'} – Meeting Brief`,dateLabel(),'','HLAVNÍ ZÁVĚR',a.executive||''];const add=(title,arr)=>{if(arr?.length){out.push('',title,...arr.map(x=>'• '+x))}};add('DOHODNUTO',a.decisions);add('OTEVŘENÉ BODY',a.openPoints);if(a.tasks?.length){out.push('','ÚKOLY',...a.tasks.map(t=>`• ${t.task} — ${t.owner||t.side||'doplnit'} — ${t.deadline||'doplnit'}`))}add('CO JSEM SLÍBIL',a.myPromises);add('DŮLEŽITÁ ČÍSLA',a.numbers);add('POŽADAVKY ZÁKAZNÍKA',a.customerRequests);add('POZICE HOPI',a.hopiPosition);add('RIZIKA',a.risks);add('FOLLOW-UP',a.followUp);return out.join('\n')}
function customerEmail(){const a=state.analysis||{};const customer=$('customerName')?.value.trim()||'';const out=['Dobrý den,','',`děkuji za dnešní jednání${customer?' se společností '+customer:''}. Níže zasílám stručné shrnutí:`,''];if(a.decisions?.length){out.push('Dohodnuto:');a.decisions.forEach(x=>out.push('• '+x));out.push('')}if(a.tasks?.length){out.push('Další kroky:');a.tasks.forEach(t=>out.push(`• ${t.task}${t.owner?' – '+t.owner:''}${t.deadline?' – '+t.deadline:''}`));out.push('')}if(a.openPoints?.length){out.push('Otevřené body:');a.openPoints.forEach(x=>out.push('• '+x));out.push('')}out.push('Děkuji a přeji hezký den.','','S pozdravem');return out.join('\n')}
function openMail(){if(!state.analysis)return toast('Nejdřív vytvoř Meeting Brief.');const to=$('emailTo')?.value.trim()||'';location.href=`mailto:${encodeURIComponent(to)}?subject=${encodeURIComponent('Shrnutí jednání – '+(state.analysis.title||'Meeting'))}&body=${encodeURIComponent(customerEmail())}`}
async function copySummary(){try{await navigator.clipboard.writeText(plainSummary());toast('Shrnutí zkopírováno.')}catch{toast('Kopírování se nepodařilo.')}}
async function shareSummary(){if(navigator.share){try{await navigator.share({title:state.analysis?.title||'Meeting Brief',text:plainSummary()})}catch{}}else copySummary()}

function doneMap(){try{return JSON.parse(localStorage.getItem(DONE_KEY)||'{}')}catch{return{}}}
function setPromiseDone(key,value){const d=doneMap();d[key]=value;localStorage.setItem(DONE_KEY,JSON.stringify(d));renderPromises()}
function renderPromises(){const box=$('promiseList');if(!box)return;const d=doneMap();const rows=[];history().forEach(m=>(m.analysis?.myPromises||[]).forEach((p,i)=>rows.push({key:`${m.id}:${i}:${p}`,text:p,customer:m.customer,title:m.title,date:m.date,done:!!d[`${m.id}:${i}:${p}`]})));$('promiseCount').textContent=String(rows.filter(x=>!x.done).length);box.innerHTML='';if(!rows.length){box.innerHTML='<div class="empty">Zatím tu nejsou žádné zachycené závazky.</div>';return}rows.sort((a,b)=>Number(a.done)-Number(b.done)||b.date-a.date).forEach(r=>{const c=document.createElement('div');c.className='compact-card promise-item';c.innerHTML=`<input type="checkbox" ${r.done?'checked':''}><div><strong>${esc(r.text)}</strong><small>${esc(r.customer||'Bez zákazníka')} · ${esc(dateLabel(r.date))}</small></div>`;c.querySelector('input').onchange=e=>setPromiseDone(r.key,e.target.checked);box.appendChild(c)})}
function renderCustomers(){const box=$('customerHistory');if(!box)return;const h=history();$('historyCount').textContent=String(h.length);box.innerHTML='';if(!h.length){box.innerHTML='<div class="empty">Zatím tu nejsou žádné uložené meetingy.</div>';return}const groups={};h.forEach(m=>{const k=m.customer||'Bez zákazníka';(groups[k]||(groups[k]=[])).push(m)});Object.entries(groups).forEach(([customer,items])=>{const g=document.createElement('div');g.className='customer-group';g.innerHTML=`<h3>${esc(customer)} <small>(${items.length})</small></h3><div class="compact-list"></div>`;const list=g.querySelector('.compact-list');items.forEach(item=>{const c=document.createElement('div');c.className='compact-card';c.innerHTML=`<strong>${esc(item.title||'Meeting')}</strong><small>${esc(dateLabel(item.date))}</small><p>${esc(item.analysis?.executive||'')}</p>`;c.onclick=()=>loadHistory(item);list.appendChild(c)});box.appendChild(g)})}
function loadHistory(item){resetMeeting();state.currentId=item.id;state.analysis=item.analysis;state.transcript=item.transcript||'';$('customerName').value=item.customer||'';$('emailTo').value=item.email||'';renderBrief()}

$('startBtn').onclick=startMeeting;$('importantBtn').onclick=addImportantMarker;$('briefBackBtn').onclick=()=>showView('homeView');$('emailBtn').onclick=openMail;$('copyBtn').onclick=copySummary;$('shareBtn').onclick=shareSummary;$('pdfBtn').onclick=()=>window.print();$('settingsTopBtn').onclick=()=>showView('settingsView');$('clearHistoryBtn').onclick=()=>{if(confirm('Opravdu smazat historii meetingů v tomto zařízení?')){localStorage.removeItem(STORAGE_KEY);localStorage.removeItem(DONE_KEY);renderPromises();renderCustomers();toast('Historie byla smazána.')}};document.querySelectorAll('.nav-btn').forEach(b=>b.onclick=()=>showView(b.dataset.view));document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.tab-panel').forEach(x=>x.classList.remove('active'));b.classList.add('active');$(b.dataset.tab==='summary'?'summaryTab':'sourceTab').classList.add('active')});
renderPromises();renderCustomers();if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));

window.HOPI_APP={state,showView,toast,finishRecording,renderBrief,previousContext,history};
